// Migration to update will steps fields
const { sql } = require('kysely');

const up = async (db) => {
// Will fields
  await sql`ALTER TABLE wills DROP COLUMN IF EXISTS jurisdiction`.execute(db); 
// Testators field
  await sql`ALTER TABLE testators DROP COLUMN IF EXISTS first_name`.execute(db);
  await sql`ALTER TABLE testators DROP COLUMN IF EXISTS middle_name`.execute(db);
  await sql`ALTER TABLE testators DROP COLUMN IF EXISTS last_name`.execute(db);
  await sql`ALTER TABLE testators DROP COLUMN IF EXISTS father_name`.execute(db);
  await sql`ALTER TABLE testators DROP COLUMN IF EXISTS husband_name`.execute(db);
  await sql`ALTER TABLE testators DROP COLUMN IF EXISTS has_property_abroad`.execute(db);
  await sql`ALTER TABLE testators DROP COLUMN IF EXISTS address_line_1`.execute(db);
  await sql`ALTER TABLE testators DROP COLUMN IF EXISTS address_line_2`.execute(db);
  await sql`ALTER TABLE testators DROP COLUMN IF EXISTS jurisdiction`.execute(db);
  await sql`ALTER TABLE testators ADD COLUMN IF NOT EXISTS jurisdiction_country varchar(50)`.execute(db);
  await sql`ALTER TABLE testators ADD COLUMN IF NOT EXISTS jurisdiction_region varchar(50)`.execute(db);
// Executors field
  await sql`ALTER TABLE executors DROP COLUMN IF EXISTS building_number`.execute(db);
  await sql`ALTER TABLE executors DROP COLUMN IF EXISTS building_name`.execute(db);
  await sql`ALTER TABLE executors DROP COLUMN IF EXISTS street`.execute(db);
  await sql`ALTER TABLE executors DROP COLUMN IF EXISTS town`.execute(db);
  await sql`ALTER TABLE executors DROP COLUMN IF EXISTS city`.execute(db);
  await sql`ALTER TABLE executors DROP COLUMN IF EXISTS county`.execute(db);
  await sql`ALTER TABLE executors DROP COLUMN IF EXISTS postcode`.execute(db);
  await sql`ALTER TABLE executors DROP COLUMN IF EXISTS country`.execute(db);
  await sql`ALTER TABLE executors DROP COLUMN IF EXISTS address_line_1`.execute(db);
  await sql`ALTER TABLE executors DROP COLUMN IF EXISTS address_line_2`.execute(db);
  await sql`ALTER TABLE executors DROP COLUMN IF EXISTS is_spouse`.execute(db);
// Spouses field
  await sql`ALTER TABLE spouses ADD COLUMN IF NOT EXISTS order_index integer DEFAULT 0`.execute(db);
  await sql`ALTER TABLE spouses DROP COLUMN IF EXISTS is_same_address`.execute(db);
  await sql`ALTER TABLE spouses DROP COLUMN IF EXISTS address_line_1`.execute(db);
  await sql`ALTER TABLE spouses DROP COLUMN IF EXISTS address_line_2`.execute(db);
  await sql`ALTER TABLE spouses DROP COLUMN IF EXISTS is_spouse`.execute(db);
// Cildren field
await sql`ALTER TABLE children ADD COLUMN IF NOT EXISTS title varchar(20)`.execute(db);
await sql`ALTER TABLE children ADD COLUMN IF NOT EXISTS gender varchar(50)`.execute(db);
  await sql`ALTER TABLE children ADD COLUMN IF NOT EXISTS building_number varchar(50)`.execute(db);
  await sql`ALTER TABLE children ADD COLUMN IF NOT EXISTS building_name varchar(100)`.execute(db);
  await sql`ALTER TABLE children ADD COLUMN IF NOT EXISTS street varchar(255)`.execute(db);
  await sql`ALTER TABLE children ADD COLUMN IF NOT EXISTS town varchar(100)`.execute(db);
  await sql`ALTER TABLE children ADD COLUMN IF NOT EXISTS city varchar(255)`.execute(db);
  await sql`ALTER TABLE children ADD COLUMN IF NOT EXISTS county varchar(100)`.execute(db);
  await sql`ALTER TABLE children ADD COLUMN IF NOT EXISTS postcode varchar(20)`.execute(db);
  await sql`ALTER TABLE children ADD COLUMN IF NOT EXISTS country varchar(100)`.execute(db);
  await sql`ALTER TABLE children ADD COLUMN IF NOT EXISTS relationship_to_testator varchar(100)`.execute(db);
  await sql`ALTER TABLE children ADD COLUMN IF NOT EXISTS inheritance_age integer`.execute(db);
  await sql`ALTER TABLE children ADD COLUMN IF NOT EXISTS order_index integer DEFAULT 0`.execute(db);
  await sql`ALTER TABLE children DROP COLUMN IF EXISTS is_minor`.execute(db);
  await sql`ALTER TABLE children DROP COLUMN IF EXISTS is_dependent`.execute(db);
// Guardians field
  await sql`ALTER TABLE guardians ADD COLUMN IF NOT EXISTS title varchar(20)`.execute(db);
  await sql`ALTER TABLE guardians ADD COLUMN IF NOT EXISTS date_of_birth varchar(10)`.execute(db);
  await sql`ALTER TABLE guardians ADD COLUMN IF NOT EXISTS building_number varchar(50)`.execute(db);
  await sql`ALTER TABLE guardians ADD COLUMN IF NOT EXISTS building_name varchar(100)`.execute(db);
  await sql`ALTER TABLE guardians ADD COLUMN IF NOT EXISTS street varchar(255)`.execute(db);
  await sql`ALTER TABLE guardians ADD COLUMN IF NOT EXISTS town varchar(100)`.execute(db);
  await sql`ALTER TABLE guardians ADD COLUMN IF NOT EXISTS email varchar(255)`.execute(db);
  await sql`ALTER TABLE guardians ADD COLUMN IF NOT EXISTS phone_country_code varchar(10)`.execute(db);
  await sql`ALTER TABLE guardians ADD COLUMN IF NOT EXISTS phone varchar(30)`.execute(db);
  await sql`ALTER TABLE guardians ADD COLUMN IF NOT EXISTS is_alternate boolean DEFAULT false`.execute(db);
  await sql`ALTER TABLE guardians DROP COLUMN IF EXISTS address_line_1`.execute(db);
  await sql`ALTER TABLE guardians DROP COLUMN IF EXISTS address_line_2`.execute(db);
  await sql`ALTER TABLE guardians DROP COLUMN IF EXISTS is_substitute`.execute(db);
// Trustees field
  await sql`ALTER TABLE trustees ADD COLUMN IF NOT EXISTS title varchar(20)`.execute(db);
  await sql`ALTER TABLE trustees ADD COLUMN IF NOT EXISTS date_of_birth varchar(10)`.execute(db);
  await sql`ALTER TABLE trustees ADD COLUMN IF NOT EXISTS building_number varchar(50)`.execute(db);
  await sql`ALTER TABLE trustees ADD COLUMN IF NOT EXISTS building_name varchar(100)`.execute(db);
  await sql`ALTER TABLE trustees ADD COLUMN IF NOT EXISTS street varchar(255)`.execute(db);
  await sql`ALTER TABLE trustees ADD COLUMN IF NOT EXISTS town varchar(100)`.execute(db);
  await sql`ALTER TABLE trustees ADD COLUMN IF NOT EXISTS phone_country_code varchar(10)`.execute(db);
  await sql`ALTER TABLE trustees ADD COLUMN IF NOT EXISTS phone varchar(30)`.execute(db);
  await sql`ALTER TABLE trustees ADD COLUMN IF NOT EXISTS role_type varchar(50)`.execute(db);
  await sql`ALTER TABLE trustees ADD COLUMN IF NOT EXISTS include_all_general_powers boolean DEFAULT false`.execute(db);
  await sql`ALTER TABLE trustees ADD COLUMN IF NOT EXISTS power_of_management boolean DEFAULT false`.execute(db);
  await sql`ALTER TABLE trustees ADD COLUMN IF NOT EXISTS power_of_investment boolean DEFAULT false`.execute(db);
  await sql`ALTER TABLE trustees ADD COLUMN IF NOT EXISTS power_to_delegate boolean DEFAULT false`.execute(db);
  await sql`ALTER TABLE trustees ADD COLUMN IF NOT EXISTS power_in_relation_to_property boolean DEFAULT false`.execute(db);
  await sql`ALTER TABLE trustees ADD COLUMN IF NOT EXISTS power_to_lend_and_borrow boolean DEFAULT false`.execute(db);
  await sql`ALTER TABLE trustees ADD COLUMN IF NOT EXISTS power_to_apply_income_for_minors boolean DEFAULT false`.execute(db);
  await sql`ALTER TABLE trustees ADD COLUMN IF NOT EXISTS power_to_make_advancements boolean DEFAULT false`.execute(db);
  await sql`ALTER TABLE trustees ADD COLUMN IF NOT EXISTS power_to_appropriate_assets boolean DEFAULT false`.execute(db);
  await sql`ALTER TABLE trustees ADD COLUMN IF NOT EXISTS power_to_act_by_majority boolean DEFAULT false`.execute(db);
  await sql`ALTER TABLE trustees ADD COLUMN IF NOT EXISTS power_to_charge boolean DEFAULT false`.execute(db);
  await sql`ALTER TABLE trustees ADD COLUMN IF NOT EXISTS power_to_invest_in_non_interest_accounts boolean DEFAULT false`.execute(db);
  await sql`ALTER TABLE trustees ADD COLUMN IF NOT EXISTS additional_powers text`.execute(db);
  await sql`ALTER TABLE trustees DROP COLUMN IF EXISTS address_line_1`.execute(db);
  await sql`ALTER TABLE trustees DROP COLUMN IF EXISTS address_line_2`.execute(db);
// Beneficiary field
  await sql`ALTER TABLE beneficiaries ADD COLUMN IF NOT EXISTS title varchar(20)`.execute(db);
  await sql`ALTER TABLE beneficiaries ADD COLUMN IF NOT EXISTS building_number varchar(50)`.execute(db);
  await sql`ALTER TABLE beneficiaries ADD COLUMN IF NOT EXISTS building_name varchar(100)`.execute(db);
  await sql`ALTER TABLE beneficiaries ADD COLUMN IF NOT EXISTS street varchar(255)`.execute(db);
  await sql`ALTER TABLE beneficiaries ADD COLUMN IF NOT EXISTS town varchar(100)`.execute(db);
  await sql`ALTER TABLE beneficiaries ADD COLUMN IF NOT EXISTS phone_country_code varchar(10)`.execute(db);
  await sql`ALTER TABLE beneficiaries ADD COLUMN IF NOT EXISTS phone varchar(30)`.execute(db);
  await sql`ALTER TABLE beneficiaries ADD COLUMN IF NOT EXISTS email varchar(255)`.execute(db);
  await sql`ALTER TABLE beneficiaries DROP COLUMN IF EXISTS address_line_1`.execute(db);
  await sql`ALTER TABLE beneficiaries DROP COLUMN IF EXISTS address_line_2`.execute(db);
  await sql`ALTER TABLE beneficiaries DROP COLUMN IF EXISTS beneficary_type`.execute(db);
  await sql`ALTER TABLE beneficiaries DROP COLUMN IF EXISTS is_remainder_beneficary`.execute(db);
  await sql`ALTER TABLE beneficiaries DROP COLUMN IF EXISTS pass_to_children_if_deceased`.execute(db);
  await sql`ALTER TABLE beneficiaries DROP COLUMN IF EXISTS share_percentage`.execute(db);
  await sql`ALTER TABLE beneficiaries DROP COLUMN IF EXISTS specific_gift_description`.execute(db);
  await sql`ALTER TABLE beneficiaries DROP COLUMN IF EXISTS inheritance_age`.execute(db);
  await sql`ALTER TABLE beneficiaries DROP COLUMN IF EXISTS alternate_for_id`.execute(db);
// Charity field
  await sql`ALTER TABLE charities ADD COLUMN IF NOT EXISTS address varchar(255)`.execute(db);
  await sql`ALTER TABLE charities DROP COLUMN IF EXISTS address_line_1`.execute(db);
  await sql`ALTER TABLE charities DROP COLUMN IF EXISTS address_line_2`.execute(db);
  await sql`ALTER TABLE charities DROP COLUMN IF EXISTS city`.execute(db);
  await sql`ALTER TABLE charities DROP COLUMN IF EXISTS postcode`.execute(db);
  await sql`ALTER TABLE charities DROP COLUMN IF EXISTS country`.execute(db);
  await sql`ALTER TABLE charities DROP COLUMN IF EXISTS alternate_for_id`.execute(db);
};

const down = async (db) => {
  await sql`ALTER TABLE wills ADD COLUMN IF NOT EXISTS jurisdiction varchar(50)`.execute(db);
  await sql`ALTER TABLE testators ADD COLUMN IF NOT EXISTS jurisdiction varchar(50)`.execute(db);
  await sql`ALTER TABLE testators ADD COLUMN IF NOT EXISTS first_name varchar(100)`.execute(db);
  await sql`ALTER TABLE testators ADD COLUMN IF NOT EXISTS middle_name varchar(100)`.execute(db);
  await sql`ALTER TABLE testators ADD COLUMN IF NOT EXISTS last_name varchar(100)`.execute(db);
  await sql`ALTER TABLE testators ADD COLUMN IF NOT EXISTS father_name varchar(100)`.execute(db);
  await sql`ALTER TABLE testators ADD COLUMN IF NOT EXISTS husband_name varchar(100)`.execute(db);
  await sql`ALTER TABLE testators ADD COLUMN IF NOT EXISTS has_property_abroad boolean DEFAULT false`.execute(db);
  await sql`ALTER TABLE testators ADD COLUMN IF NOT EXISTS address_line_1 varchar(255)`.execute(db);
  await sql`ALTER TABLE testators ADD COLUMN IF NOT EXISTS address_line_2 varchar(255)`.execute(db);
  await sql`ALTER TABLE executors ADD COLUMN IF NOT EXISTS address_line_1 varchar(255)`.execute(db);
  await sql`ALTER TABLE executors ADD COLUMN IF NOT EXISTS address_line_2 varchar(255)`.execute(db);
  await sql`ALTER TABLE executors ADD COLUMN IF NOT EXISTS building_number varchar(50)`.execute(db);
  await sql`ALTER TABLE executors ADD COLUMN IF NOT EXISTS building_name varchar(100)`.execute(db);
  await sql`ALTER TABLE executors ADD COLUMN IF NOT EXISTS street varchar(255)`.execute(db);
  await sql`ALTER TABLE executors ADD COLUMN IF NOT EXISTS town varchar(100)`.execute(db);
  await sql`ALTER TABLE executors ADD COLUMN IF NOT EXISTS city varchar(255)`.execute(db);
  await sql`ALTER TABLE executors ADD COLUMN IF NOT EXISTS county varchar(100)`.execute(db);
  await sql`ALTER TABLE executors ADD COLUMN IF NOT EXISTS postcode varchar(20)`.execute(db);
  await sql`ALTER TABLE executors ADD COLUMN IF NOT EXISTS country varchar(100)`.execute(db);
  await sql`ALTER TABLE executors ADD COLUMN IF NOT EXISTS is_spouse boolean DEFAULT false`.execute(db);
  await sql`ALTER TABLE spouses ADD COLUMN IF NOT EXISTS is_same_address boolean DEFAULT true`.execute(db);
  await sql`ALTER TABLE spouses ADD COLUMN IF NOT EXISTS address_line_1 varchar(255)`.execute(db);
  await sql`ALTER TABLE spouses ADD COLUMN IF NOT EXISTS address_line_2 varchar(255)`.execute(db);
  await sql`ALTER TABLE spouses ADD COLUMN IF NOT EXISTS is_spouse boolean DEFAULT false`.execute(db);
  await sql`ALTER TABLE guardians ADD COLUMN IF NOT EXISTS address_line_1 varchar(255)`.execute(db);
  await sql`ALTER TABLE guardians ADD COLUMN IF NOT EXISTS address_line_2 varchar(255)`.execute(db);
  await sql`ALTER TABLE guardians ADD COLUMN IF NOT EXISTS is_substitute boolean DEFAULT false`.execute(db);
  await sql`ALTER TABLE guardians ADD COLUMN IF NOT EXISTS beneficary_type`.execute(db);
  await sql`ALTER TABLE guardians ADD COLUMN IF NOT EXISTS is_remainder_beneficary boolean DEFAULT false`.execute(db);
  await sql`ALTER TABLE guardians ADD COLUMN IF NOT EXISTS pass_to_children_if_deceased boolean DEFAULT true`.execute(db);
  await sql`ALTER TABLE guardians ADD COLUMN IF NOT EXISTS share_percentage numeric`.execute(db);
  await sql`ALTER TABLE guardians ADD COLUMN IF NOT EXISTS specific_gift_description text`.execute(db);
  await sql`ALTER TABLE guardians ADD COLUMN IF NOT EXISTS inheritance_age integer`.execute(db);
  await sql`ALTER TABLE children ADD COLUMN IF NOT EXISTS is_minor boolean DEFAULT false`.execute(db);
  await sql`ALTER TABLE children ADD COLUMN IF NOT EXISTS is_dependent boolean DEFAULT false`.execute(db);
  await sql`ALTER TABLE trustees ADD COLUMN IF NOT EXISTS address_line_1 varchar(255)`.execute(db);
  await sql`ALTER TABLE trustees ADD COLUMN IF NOT EXISTS address_line_2 varchar(255)`.execute(db);
  await sql`ALTER TABLE trustees ADD COLUMN IF NOT EXISTS additional_powers text`.execute(db);
  await sql`ALTER TABLE beneficiaries ADD COLUMN IF NOT EXISTS address_line_1 varchar(255)`.execute(db);
  await sql`ALTER TABLE beneficiaries ADD COLUMN IF NOT EXISTS address_line_2 varchar(255)`.execute(db);
  await sql`ALTER TABLE beneficiaries ADD COLUMN IF NOT EXISTS beneficiary_type varchar(100)`.execute(db);
  await sql`ALTER TABLE beneficiaries ADD COLUMN IF NOT EXISTS is_remainder_beneficiary boolean DEFAULT false`.execute(db);
  await sql`ALTER TABLE beneficiaries ADD COLUMN IF NOT EXISTS pass_to_children_if_deceased boolean DEFAULT true`.execute(db);
  await sql`ALTER TABLE beneficiaries ADD COLUMN IF NOT EXISTS share_percentage numeric`.execute(db);
  await sql`ALTER TABLE beneficiaries ADD COLUMN IF NOT EXISTS specific_gift_description text`.execute(db);
  await sql`ALTER TABLE beneficiaries ADD COLUMN IF NOT EXISTS inheritance_age integer`.execute(db);
  await sql`ALTER TABLE beneficiaries ADD COLUMN IF NOT EXISTS alternate_for_id uuid`.execute(db);
  await sql`ALTER TABLE charities ADD COLUMN IF NOT EXISTS address_line_1 varchar(255)`.execute(db);
  await sql`ALTER TABLE charities ADD COLUMN IF NOT EXISTS address_line_2 varchar(255)`.execute(db);
  await sql`ALTER TABLE charities ADD COLUMN IF NOT EXISTS city varchar(255)`.execute(db);
  await sql`ALTER TABLE charities ADD COLUMN IF NOT EXISTS postcode varchar(20)`.execute(db);
  await sql`ALTER TABLE charities ADD COLUMN IF NOT EXISTS country varchar(100)`.execute(db);
  await sql`ALTER TABLE charities ADD COLUMN IF NOT EXISTS alternate_for_id uuid`.execute(db);

  await sql`ALTER TABLE testators DROP COLUMN IF EXISTS jurisdiction_country`.execute(db);
  await sql`ALTER TABLE testators DROP COLUMN IF EXISTS jurisdiction_region`.execute(db);
  await sql`ALTER TABLE spouses DROP COLUMN IF EXISTS order_index`.execute(db);
  await sql`ALTER TABLE children DROP COLUMN IF EXISTS title`.execute(db);
  await sql`ALTER TABLE children DROP COLUMN IF EXISTS gender`.execute(db);
  await sql`ALTER TABLE children DROP COLUMN IF EXISTS building_number`.execute(db);
  await sql`ALTER TABLE children DROP COLUMN IF EXISTS building_name`.execute(db);
  await sql`ALTER TABLE children DROP COLUMN IF EXISTS street`.execute(db);
  await sql`ALTER TABLE children DROP COLUMN IF EXISTS town`.execute(db);
  await sql`ALTER TABLE children DROP COLUMN IF EXISTS city`.execute(db);
  await sql`ALTER TABLE children DROP COLUMN IF EXISTS county`.execute(db);
  await sql`ALTER TABLE children DROP COLUMN IF EXISTS postcode`.execute(db);
  await sql`ALTER TABLE children DROP COLUMN IF EXISTS country`.execute(db);
  await sql`ALTER TABLE children DROP COLUMN IF EXISTS relationship_to_testator`.execute(db);
  await sql`ALTER TABLE children DROP COLUMN IF EXISTS order_index`.execute(db);
  await sql`ALTER TABLE children DROP COLUMN IF EXISTS inheritance_age`.execute(db);
  await sql`ALTER TABLE guardians DROP COLUMN IF EXISTS title`.execute(db);
  await sql`ALTER TABLE guardians DROP COLUMN IF EXISTS date_of_birth`.execute(db);
  await sql`ALTER TABLE guardians DROP COLUMN IF EXISTS building_number`.execute(db);
  await sql`ALTER TABLE guardians DROP COLUMN IF EXISTS building_name`.execute(db);
  await sql`ALTER TABLE guardians DROP COLUMN IF EXISTS street`.execute(db);
  await sql`ALTER TABLE guardians DROP COLUMN IF EXISTS town`.execute(db);
  await sql`ALTER TABLE guardians DROP COLUMN IF EXISTS email`.execute(db);
  await sql`ALTER TABLE guardians DROP COLUMN IF EXISTS phone_country_code`.execute(db);
  await sql`ALTER TABLE guardians DROP COLUMN IF EXISTS phone`.execute(db);
  await sql`ALTER TABLE guardians DROP COLUMN IF EXISTS is_alternate`.execute(db);
  await sql`ALTER TABLE trustees DROP COLUMN IF EXISTS title`.execute(db);
  await sql`ALTER TABLE trustees DROP COLUMN IF EXISTS date_of_birth`.execute(db);
  await sql`ALTER TABLE trustees DROP COLUMN IF EXISTS building_number`.execute(db);
  await sql`ALTER TABLE trustees DROP COLUMN IF EXISTS building_name`.execute(db);
  await sql`ALTER TABLE trustees DROP COLUMN IF EXISTS street`.execute(db);
  await sql`ALTER TABLE trustees DROP COLUMN IF EXISTS town`.execute(db);
  await sql`ALTER TABLE trustees DROP COLUMN IF EXISTS phone_country_code`.execute(db);
  await sql`ALTER TABLE trustees DROP COLUMN IF EXISTS phone`.execute(db);
  await sql`ALTER TABLE trustees DROP COLUMN IF EXISTS role_type`.execute(db);
  await sql`ALTER TABLE trustees DROP COLUMN IF EXISTS include_all_general_powers`.execute(db);
  await sql`ALTER TABLE trustees DROP COLUMN IF EXISTS power_of_management`.execute(db);
  await sql`ALTER TABLE trustees DROP COLUMN IF EXISTS power_of_investment`.execute(db);
  await sql`ALTER TABLE trustees DROP COLUMN IF EXISTS power_to_delegate`.execute(db);
  await sql`ALTER TABLE trustees DROP COLUMN IF EXISTS power_in_relation_to_property`.execute(db);
  await sql`ALTER TABLE trustees DROP COLUMN IF EXISTS power_to_lend_and_borrow`.execute(db);
  await sql`ALTER TABLE trustees DROP COLUMN IF EXISTS power_to_apply_income_for_minors`.execute(db);
  await sql`ALTER TABLE trustees DROP COLUMN IF EXISTS power_to_make_advancements`.execute(db);
  await sql`ALTER TABLE trustees DROP COLUMN IF EXISTS power_to_appropriate_assets`.execute(db);
  await sql`ALTER TABLE trustees DROP COLUMN IF EXISTS power_to_act_by_majority`.execute(db);
  await sql`ALTER TABLE trustees DROP COLUMN IF EXISTS power_to_charge`.execute(db);
  await sql`ALTER TABLE trustees DROP COLUMN IF EXISTS power_to_invest_in_non_interest_accounts`.execute(db);
  await sql`ALTER TABLE trustees DROP COLUMN IF EXISTS additional_powers`.execute(db);
  await sql`ALTER TABLE beneficiaries DROP COLUMN IF EXISTS title`.execute(db);
  await sql`ALTER TABLE beneficiaries DROP COLUMN IF EXISTS building_number`.execute(db);
  await sql`ALTER TABLE beneficiaries DROP COLUMN IF EXISTS building_name`.execute(db);
  await sql`ALTER TABLE beneficiaries DROP COLUMN IF EXISTS street`.execute(db);
  await sql`ALTER TABLE beneficiaries DROP COLUMN IF EXISTS town`.execute(db);
  await sql`ALTER TABLE beneficiaries DROP COLUMN IF EXISTS phone_country_code`.execute(db);
  await sql`ALTER TABLE beneficiaries DROP COLUMN IF EXISTS phone`.execute(db);
  await sql`ALTER TABLE beneficiaries DROP COLUMN IF EXISTS email`.execute(db);
  await sql`ALTER TABLE charities DROP COLUMN IF EXISTS address`.execute(db);
};

module.exports = { up, down };